name: wavevit_1
savepath: v0
epoches: 200
strategy: ddp
accumulate_batches: 1
precision: 16
gradient_clip_val: 5.0
data_config:
  batch_size: 64
  val_batch_size: 64
  dataroot: /neodata/pathology_breast/caltech/256_ObjectCategories/
  datalist: /neodata/pathology_breast/caltech/project/prepare/datalist.json
  cache: false
  transforms_config:
    img_size: 224
    random_transform: true
model_config:
  model:
    num_classes: 256
    backbone: wavevit_s
    backbone_num_features: 1000
  loss: FL
  optimizer: adamw
  lr: 0.00001
  scheduler:
    name: cosine
    T_max: 50
    eta_min: 0
ckpt: ../checkpoint/v0/wavecit_1/acc.ckpt
